### ISSUE TITLE
How to get cost of generation using the SDK

### ISSUE THREAD

**Issue by rsmekala** [google-gemini/generative-ai-python#215]
### Actual vs expected behavior:

I wanted to calculate the cost of generation when using `Google Gemini`. When I use the API it's response contains a field called `UsageMetadata`. Is this available in the SDK as well ??

**Comment by rsmekala** [comment]
@MarkDaoust i see you had raised a commit that mentioned this attribute. #105

**Comment by MarkDaoust** [comment]
Yeah, it was ot ready to release at that time. It should work now.

https://github.com/google-gemini/generative-ai-python/pull/315

For the question of price see https://ai.google.dev/pricing

**Comment by rubmz** [comment]
**### This bug should be re-opened!**
The metadata provided is far from easy to use for calculating the cost of the calls.
To use it I must hold a table which I update myself of the various models and their pricing in normal mode + thinking mode, and then I need to manually figure out what are the fields of the metadata to multiply with the table and then sum up (inconveniently the metadata provides "total tokens" which is **completely useles!** because pricing is different for request and response...)

**Why make use all this hard work when you already do this on the server side anyway? Why not just provide it in good old USD$ ?**
